[project]
name = "task-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artem Sarkisian", email = "artem.sarkisian517@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
task-cli = "main:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["task_tracker"]
py-modules = ["main"]

[tool.setuptools.package-dir]
task_tracker = "src/task_tracker"